name: cgadart
description: Tools for the CGA cryptocurrencies including key generation, signing, encryption, and more.
version: 1.0.1
homepage: https://www.cgacoin.net
author: CGA COIN <hello@cgacoin.net>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  pointycastle: ^1.0.1
  hex: ^0.1.2
  convert: ^2.1.1
  fixnum: ^0.10.9
  bip39: ^1.0.3

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.14.2
